export const Props = {
  display: true,
  title: "The title",
  error: true,
  message: "Following Items failed while processing the task!",
  messageBody: {
    1: "RandomMessage",
    2: "RandomMessage",
    3: "RandomMessage",
    4: "RandomMessage",
    5: "RandomMessage",
    6: "RandomMessage",
    7: "RandomMessage",
    8: "RandomMessage",
    9: "RandomMessage",
    10: "RandomMessage",
    11: "RandomMessage",
    12: "RandomMessage",
    13: "RandomMessage",
    14: "RandomMessage",
    15: "RandomMessage",
    16: "RandomMessage",
    17: "RandomMessage",
    18: "RandomMessage",
    19: "RandomMessage",
    20: "RandomMessage",
    21: "RandomMessage",
    22: "RandomMessage",
    23: "RandomMessage",
    24: "RandomMessage",
    25: "RandomMessage",
    26: "RandomMessage",
    27: "RandomMessage",
    28: "RandomMessage",
    29: "RandomMessage",
    30: "RandomMessage",
    31: "RandomMessage",
    32: "RandomMessage",
    33: "RandomMessage",
    34: "RandomMessage",
    35: "RandomMessage",
    36: "RandomMessage",
    37: "RandomMessage",
    38: "RandomMessage",
    39: "RandomMessage",
    40: "RandomMessage",
  },
  accept: true,
  acceptText: "Okay",
  onAcceptArgs: [],
  onAccept: () => {},
  reject: true,
  rejectText: "Nope",
  onRejectArgs: [],
  onReject: () => {},
  close: true,
  closeText: "Close",
  onCloseArgs: [],
  onClose: () => {},
};
