export const columns = [
  {
    headerName: "Name",
    isDisableEdit: true,
    dataKey: "name",
    type: "text",
    minWidth: 200,
    flexWidth: 2,
    sortable: true,
    sortComparator: (valA, valB, rowA, rowB) => {},
    inputValidator: (event, row) => {},
  },
  {
    headerName: "Facility",
    isDisableEdit: true,
    dataKey: "facility",
    type: "text",
    minWidth: 200,
    flexWidth: 2,
    sortable: true,
    sortComparator: (valA, valB, rowA, rowB) => {},
    inputValidator: (event, row) => {},
  },
  {
    headerName: "Priority",
    isDisableEdit: true,
    dataKey: "priority",
    type: "text",
    minWidth: 200,
    flexWidth: 2,
    sortable: true,
    sortComparator: (valA, valB, rowA, rowB) => {},
    inputValidator: (event, row) => {},
  },
  {
    headerName: "Server",
    isDisableEdit: true,
    dataKey: "server",
    type: "text",
    minWidth: 200,
    flexWidth: 2,
    sortable: true,
    sortComparator: (valA, valB, rowA, rowB) => {},
    inputValidator: (event, row) => {},
  },
  {
    headerName: "Port",
    isDisableEdit: true,
    dataKey: "port",
    type: "text",
    minWidth: 200,
    flexWidth: 2,
    sortable: true,
    sortComparator: (valA, valB, rowA, rowB) => {},
    inputValidator: (event, row) => {},
  },
  {
    headerName: "Action",
    dataKey: "__action",
    type: "actions",
    minWidth: 100,
    headerAlignment: "center",
    contentAlignment: "left",
    sortable: false,
    actions: [
      {
        type: "__delete",
        name: "Delete Syslog",
        handleDelete: () => {},
      },
    ],
  },
];
