export const rows = [
  {
    id: 1,
    name: "Micheal Scott",
    group: "Regional Manager, Telemarketer",
    trustlevel: 7,
    ipaddress: "46.66.170.187/04",
    comment:
      "A good manager doesn't fire people. He hires people and inspires people. … People, Ryan. And people will never go out of business.",
    tcptagging: "FIN",
    remotekey: "False",
    enabled: "False",
    date: "1992-05-06",
    time: "07:30 PM",
    "date-time": "1965-03-15T19:27",
  },
  {
    id: 2,
    name: "Holly Flax",
    group: "Human Resource, Telemarketer",
    trustlevel: 4,
    ipaddress: "6.108.245.54/72",
    comment:
      "Holly is sweet and simple, like a lady baker. I would not be surprised to find out that she had worked in a bakery before coming here. She has that kind of warmth.",
    tcptagging: "SYN",
    remotekey: "True",
    enabled: "True",
    date: "1972-05-03",
    time: "12:22 PM",
    "date-time": "1972-05-03T19:02",
  },
  {
    id: 3,
    name: "Pam Beesly",
    group: "Salesman, Telemarketer",
    trustlevel: 7,
    ipaddress: "153.80.153.98/79",
    comment:
      "I hate the idea that someone out there hates me. I even hate thinking that Al-Qaeda hates me. I think if they got to know me, they wouldn’t hate me.",
    tcptagging: "ACK",
    remotekey: "True",
    enabled: "False",
    date: "1979-25-03",
    time: "12:22 PM",
    "date-time": "1972-05-03T19:02",
  },
  {
    id: 4,
    name: "Jim Halpert",
    group: "Salesman, Co-Regional Manager",
    trustlevel: 7,
    ipaddress: "6.142.147.51/78",
    comment:
      "I hate the idea that someone out there hates me. I even hate thinking that Al-Qaeda hates me. I think if they got to know me, they wouldn’t hate me.",
    tcptagging: "ACK",
    remotekey: "True",
    enabled: "True",
    date: "1978-01-10",
    time: "12:00 AM",
    "date-time": "1972-05-03T19:02",
  },
  {
    id: 5,
    name: "Angela Martin",
    group: "Salesman, Telemarketer",
    trustlevel: 3,
    ipaddress: "131.82.218.57/74",
    comment:
      "I hate the idea that someone out there hates me. I even hate thinking that Al-Qaeda hates me. I think if they got to know me, they wouldn’t hate me.",
    tcptagging: "SEQ",
    remotekey: "False",
    enabled: "True",
    date: "1974-01-10",
    time: "01:00 PM",
    "date-time": "1974-05-03T19:02",
  },
  {
    id: 6,
    name: "Dwight Schrute",
    group: "Salesman, Co-Regional Manager",
    trustlevel: 4,
    ipaddress: "253.112.14.241/72",
    comment: `Whenever I'm about to do something, I think, "Would an idiot do that?" And if they would, I do not do that thing.`,
    tcptagging: "SEQ",
    remotekey: "True",
    enabled: "True",
    date: "1974-01-10",
    time: "01:00 PM",
    "date-time": "1974-05-03T19:02",
  },
  {
    id: 7,
    name: "Kelly Kapoor",
    group: "Salesman, Telemarketer",
    trustlevel: 3,
    ipaddress: "246.225.73.17/83",
    comment: `I talk a lot, so I've learned to just tune myself out.`,
    tcptagging: "SEQ",
    remotekey: "True",
    enabled: "True",
    date: "1983-01-10",
    time: "01:00 PM",
    "date-time": "1974-05-03T19:02",
  },
  {
    id: 8,
    name: "Ryan Howard",
    group: "Salesman, Telemarketer",
    trustlevel: 0,
    ipaddress: "246.225.73.17/83",
    comment: `If I had to I could clean out my desk in five seconds and nobody would ever know I had ever been here. And I’d forget too.`,
    tcptagging: "SEQ",
    remotekey: "True",
    enabled: "True",
    date: "1983-01-10",
    time: "01:00 PM",
    "date-time": "1974-05-03T19:02",
  },
];
